// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function GetOrganizeJob(arg1:number):Promise<main.OrganizeJobResult>;

export function GetPhoto(arg1:number):Promise<db.Photo>;

export function GetScan(arg1:number):Promise<db.ScanRun>;

export function GetThumbnailDataURL(arg1:number):Promise<string>;

export function ListDuplicates():Promise<Array<db.DuplicateGroup>>;

export function ListPhotos(arg1:main.PhotoQuery):Promise<main.PhotosResult>;

export function ListScans():Promise<Array<db.ScanRun>>;

export function PickDestinationDirectory():Promise<string>;

export function PickDirectory():Promise<string>;

export function ResolveDuplicate(arg1:number,arg2:number):Promise<void>;

export function StartOrganize(arg1:main.OrganizeRequest):Promise<main.StartOrganizeResult>;

export function StartScan(arg1:string):Promise<main.ScanResult>;
