// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOrganizeJob(arg1) {
  return window['go']['main']['App']['GetOrganizeJob'](arg1);
}

export function GetPhoto(arg1) {
  return window['go']['main']['App']['GetPhoto'](arg1);
}

export function GetScan(arg1) {
  return window['go']['main']['App']['GetScan'](arg1);
}

export function GetThumbnailDataURL(arg1) {
  return window['go']['main']['App']['GetThumbnailDataURL'](arg1);
}

export function ListDuplicates() {
  return window['go']['main']['App']['ListDuplicates']();
}

export function ListPhotos(arg1) {
  return window['go']['main']['App']['ListPhotos'](arg1);
}

export function ListScans() {
  return window['go']['main']['App']['ListScans']();
}

export function PickDestinationDirectory() {
  return window['go']['main']['App']['PickDestinationDirectory']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ResolveDuplicate(arg1, arg2) {
  return window['go']['main']['App']['ResolveDuplicate'](arg1, arg2);
}

export function StartOrganize(arg1) {
  return window['go']['main']['App']['StartOrganize'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
